---
     
- hosts: 192.168.10.142
  tasks:
    - name: Ensure apache2 is at the latest version 
      apt:
        name: apache2
        state: latest
    - name: enable and start the apache
      service:
        name: apache2
        enabled: true
        state: started
