---
     
- hosts: 192.168.10.142
  tasks:
    - name: Install apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: present
    - name: enable and start the apache
      service:
        name: apache2
        enabled: true
        state: started
