---
- hosts: 192.168.10.46
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest
        
- hosts: 192.168.10.142
  tasks:
    - name: install vsftpd
      apt:
        name: vsftpd
        state: latest
