---
- name: install httpd
  hosts: 192.168.10.47
  tasks:
    - name: create a new user
      user:
        name: ansible
        state: present
    - name: enable firewalld
      service:
        name: firewalld
        state: started
