- hosts: 192.168.10.142
  tasks:
    - name: Install MariaDB Server 10.3
      apt: name=mariadb-server state=latest
        
    - name: Install MariaDB Client 10.3
      apt: name=mariadb-client state=latest

    - name: Restart MariaDB 10.3
      service: name=mysql state=restarted
