---
- name: install httpd
  hosts: 192.168.10.47
  tasks:
    - name: create a new user
      user:
        name: redhat
        state: present
    - name: start anaconda
      service:
        name: anaconda
        enabled: true
        state: started
